#pragma once
// General
#include <iostream>
#include <memory>
#include <algorithm>
#include <functional>
#include <string>
#include <sstream>
#include <vector>
#include <map>
#include <array>
#include <unordered_map>
#include <unordered_set>
#include <cstdint>
#include <cassert>
#include <queue>
#include <bitset>
#include <fstream>
#include <set>
#include <random>
#include <tuple>

// GLM
#include <glm/glm.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <glm/gtc/matrix_transform.hpp>

// OpenGL
#include <glad/glad.h>
#include <GLFW/glfw3.h>
